"""add ml fields

Revision ID: 206e3c3e0d2a
Revises: 56b4d4ca533e
Create Date: 2026-02-25 15:42:38.851141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '206e3c3e0d2a'
down_revision: Union[str, Sequence[str], None] = '56b4d4ca533e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('loans', 'loan_status',
               existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='loanstatusenum'),
               type_=sa.String(),
               nullable=True)
    op.drop_column('loans', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('loans', 'loan_status',
               existing_type=sa.String(),
               type_=postgresql.ENUM('pending', 'approved', 'rejected', name='loanstatusenum'),
               nullable=False)
    # ### end Alembic commands ###
