"""add ml fields

Revision ID: 56b4d4ca533e
Revises: 68445f061769
Create Date: 2026-02-25 12:44:13.785642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b4d4ca533e'
down_revision: Union[str, Sequence[str], None] = '68445f061769'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('status', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('ml_score', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('decision_reason', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('model_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'model_version')
    op.drop_column('loans', 'decision_reason')
    op.drop_column('loans', 'ml_score')
    op.drop_column('loans', 'status')
    # ### end Alembic commands ###
