"""add credit history

Revision ID: 68445f061769
Revises: b8854d8a7aff
Create Date: 2026-02-22 18:24:39.950768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68445f061769'
down_revision: Union[str, Sequence[str], None] = 'b8854d8a7aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('credit_history', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'credit_history')
    # ### end Alembic commands ###
